version: "3.1"

services:
  mysqldb:
    image: mysql
    container_name: delivery-app-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB_NAME
    ports:
      - 3306:3306