version: "3.1"

services:
  db:
    image: mysql:5.7
    container_name: delivery-app-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306
    # volumes: 
    #   - ./db.example.sql:/docker-entrypoint-initdb.d/db.example.sql 