version: "3.1"

services:
  mysqldb:
    image: mysql:5.7
    container_name: delivery-app-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306